/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logins;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import logins.login_s;
/**
/**
 * 
 */
import javax.swing.JOptionPane;


/**
 *
 * @author pc12
 */
public class login_s extends javax.swing.JFrame {

    /**
     * Creates new form login_s
     */
    public login_s() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLIPSTICK = new javax.swing.JButton();
        jSPRAY = new javax.swing.JButton();
        jBRUSH = new javax.swing.JButton();
        jCONTOUR = new javax.swing.JButton();
        jLIGHTER = new javax.swing.JButton();
        jLIQUID = new javax.swing.JButton();
        jPOWDER = new javax.swing.JButton();
        jLASHES = new javax.swing.JButton();
        jSHADOW = new javax.swing.JButton();
        jMASCARA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 956, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jLIPSTICK.setText("LIPSTICK");
        jLIPSTICK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLIPSTICKActionPerformed(evt);
            }
        });

        jSPRAY.setText("HAIR SPRAY");
        jSPRAY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSPRAYActionPerformed(evt);
            }
        });

        jBRUSH.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBRUSH.setText("BRUSH");
        jBRUSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRUSHActionPerformed(evt);
            }
        });

        jCONTOUR.setText("CONTOUR");
        jCONTOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCONTOURActionPerformed(evt);
            }
        });

        jLIGHTER.setText("HIGH LIGHTER");
        jLIGHTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLIGHTERActionPerformed(evt);
            }
        });

        jLIQUID.setText("LIQUID FOUNDATION");
        jLIQUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLIQUIDActionPerformed(evt);
            }
        });

        jPOWDER.setText("POWDER");
        jPOWDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPOWDERActionPerformed(evt);
            }
        });

        jLASHES.setText("EYE LASHES");
        jLASHES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLASHESActionPerformed(evt);
            }
        });

        jSHADOW.setText("EYE SHADOW");
        jSHADOW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSHADOWActionPerformed(evt);
            }
        });

        jMASCARA.setText("MASCARA");
        jMASCARA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMASCARAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLIQUID, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSHADOW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSPRAY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLIPSTICK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBRUSH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLASHES, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(415, 415, 415)
                                .addComponent(jCONTOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLIGHTER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPOWDER, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jMASCARA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(727, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIPSTICK, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCONTOUR, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRUSH, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIQUID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSPRAY, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLIGHTER, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSHADOW, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPOWDER, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLASHES, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMASCARA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("JJMR COSMETICS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(705, 705, 705)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBRUSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRUSHActionPerformed
        String brush = jBRUSH.getText();
        String Brush = jBRUSH.getText();
        {
            jBRUSH.setText(null);
            jBRUSH.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "A makeup brush is a tool of bristles use for the application of makeup or face painting");
                jBRUSH.setText(null);
                jBRUSH.setText(null);
        }
        }
    }//GEN-LAST:event_jBRUSHActionPerformed

    private void jLIQUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLIQUIDActionPerformed
        String liquid = jLIQUID.getText();
        String Liquid = jLIQUID.getText();
        {
            jLIQUID.setText(null);
            jLIQUID.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Foundation is a multi-coloured makeup applied to the face to create an even, uniform colour to the complexion, to cover flaws and, sometimes, to change the natural skintone.");
                jLIQUID.setText(null);
                jLIQUID.setText(null);
        }
        }
    }//GEN-LAST:event_jLIQUIDActionPerformed

    private void jCONTOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCONTOURActionPerformed
        String contour = jCONTOUR.getText();
        String Contour = jCONTOUR.getText();
        {
            jCONTOUR.setText(null);
            jCONTOUR.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Contouring is a makeup technique that uses cosmetics to define, enhance and sculpt the structure of the face or other body parts.");
                jCONTOUR.setText(null);
                jCONTOUR.setText(null);
        }
        }
    }//GEN-LAST:event_jCONTOURActionPerformed

    private void jPOWDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPOWDERActionPerformed
        String powder = jPOWDER.getText();
        String Powder = jPOWDER.getText();
        {
            jPOWDER.setText(null);
            jPOWDER.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Face powder is a cosmetic powder applied to the face to set a foundation after application.");
                jPOWDER.setText(null);
                jPOWDER.setText(null);
        }
        }     
    }//GEN-LAST:event_jPOWDERActionPerformed

    private void jSHADOWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSHADOWActionPerformed
        String shadow = jSHADOW.getText();
        String Shadow = jSHADOW.getText();
        {
            jSHADOW.setText(null);
            jSHADOW.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Eye shadow is a cosmetic that is applied on the eyelids and under the eyebrows. It is commonly used to make the wearer's eyes stand out or look more attractive.");
                jSHADOW.setText(null);
                jSHADOW.setText(null);
        }
        }     
    }//GEN-LAST:event_jSHADOWActionPerformed

    private void jLIPSTICKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLIPSTICKActionPerformed
        String lipstick = jLIPSTICK.getText();
        String Lipstick = jLIPSTICK.getText();
        {
            jLIPSTICK.setText(null);
            jLIPSTICK.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Lipstick is a cosmetic product containing pigments, oils, waxes, and emollients that apply color, texture, and protection to the lips.");
                jLIPSTICK.setText(null);
                jLIPSTICK.setText(null);
        }
        }     
    }//GEN-LAST:event_jLIPSTICKActionPerformed

    private void jSPRAYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSPRAYActionPerformed
        String spray = jSPRAY.getText();
        String Spray = jSPRAY.getText();
        {
            jSPRAY.setText(null);
            jSPRAY.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Solution sprayed on to a person's hair to keep it in place.");
                jSPRAY.setText(null);
                jSPRAY.setText(null);
        }
        }     
    }//GEN-LAST:event_jSPRAYActionPerformed

    private void jLIGHTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLIGHTERActionPerformed
        String lighter = jLIGHTER.getText();
        String Lighter = jLIGHTER.getText();
        {
            jLIGHTER.setText(null);
            jLIGHTER.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Highlighter is a type of cosmetic product that reflects light. Often used for contouring, it can applied to the face or other parts of the body to brighten the skin on a given area, create the perception of depth and angles.");
                jLIGHTER.setText(null);
                jLIGHTER.setText(null);
        }
        }     
    }//GEN-LAST:event_jLIGHTERActionPerformed

    private void jLASHESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLASHESActionPerformed
        String lashes = jLASHES.getText();
        String Lashes = jLASHES.getText();
        {
            jLASHES.setText(null);
            jLASHES.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Eyelash extensions are used to enhance the length, curliness, fullness, and thickness of natural eyelashes. The extensions may be made from several materials including mink, synthetic, or horse hair.");
                jLASHES.setText(null);
                jLASHES.setText(null);
        }    
    }                                          
    }//GEN-LAST:event_jLASHESActionPerformed

    private void jMASCARAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMASCARAActionPerformed
        String mascara = jMASCARA.getText();
        String Mascara = jMASCARA.getText();
        {
            jMASCARA.setText(null);
            jMASCARA.setText (null);
            
            login_s Info = new login_s();
            Info.setVisible(true);
        {
            
           JOptionPane.showMessageDialog(null, "Mascara is a cosmetic for darkening and thickening the eyelashes");
                jMASCARA.setText(null);
                jMASCARA.setText(null);
        }
        }     
    }//GEN-LAST:event_jMASCARAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_s.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_s().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBRUSH;
    private javax.swing.JButton jCONTOUR;
    private javax.swing.JButton jLASHES;
    private javax.swing.JButton jLIGHTER;
    private javax.swing.JButton jLIPSTICK;
    private javax.swing.JButton jLIQUID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jMASCARA;
    private javax.swing.JButton jPOWDER;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jSHADOW;
    private javax.swing.JButton jSPRAY;
    // End of variables declaration//GEN-END:variables
}
